services:
  reverse-proxy:
    build:
      context: reverse-proxy
    ports:
      - "80:80"
    restart: always
    networks:
      - cocos-network
  updater:
    build:
      context: .
      dockerfile: updater/Dockerfile
    restart: always
    networks:
      - cocos-network
    depends_on:
      - reverse-proxy
networks:
  cocos-network:
    external: true