name: Coco's Concierge deployment
on:
  push:
    branches:
      - main
jobs:
  "Concierge-Deployment":
    runs-on: ubuntu-latest
    steps:
      - name: Cloning and setting up repository on Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd 
