name: Coco's Concierge deployment
on:
  push:
    branches:
      - main
jobs:
  "Concierge-Deployment":
    runs-on: ubuntu-latest
    steps:
      - name: Cloning and setting up repository on Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -x

            cd development

            # Kill the previous Updater nohup service
            kill -9 `pgrep python`

            # Stop and remove repo if it exists
            if [[ -d "cocos-concierge" ]];then cd cocos-concierge; docker compose down; cd ../; rm -rf cocos-concierge; fi
            git clone --depth 1 --branch main git@github.com:neutonfoo/cocos-concierge.git
            cd cocos-concierge

            # Start the Updater service
            cd concierge
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            nohup python app.py &>logs/concierge.app.txt &
            cd ../

            # Start reverse-proxy and certbot
            # ./reverse-proxy/nginx-conf-generator.sh
            docker compose up -d --build --force-recreate